version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: feri-timetable-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # Add your environment variables here
      # You can also use an .env file with env_file: .env
      - WISE_USERNAME=${WISE_USERNAME}
      - WISE_PASSWORD=${WISE_PASSWORD}
      - WISE_URL=${WISE_URL}
    env_file:
      - .env.local
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - feri-network

networks:
  feri-network:
    driver: bridge
